baseURL = "https://kb.zzr.ru"
languageCode = "ru-ru"
title = "База знаний"
theme = "book"
enableGitInfo = true
enableRobotsTXT = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
